### ISSUE TITLE
Store data in queryable format

### ISSUE THREAD

**Issue by GammaGames** [GamerKingFaiz/shouldiplay#1]
This might be a bit of a design shift, I haven't really looked through the code much.

It would be nice if the server could cache the data once a day, then serve that cache. It could store the most popular permutations available, before serving the cache as an SQLite database. It'd be faster to send requests to a server that processes and responds only what is needed, but if you want very few server costs it might be the way to go.

Miiiiight be able to run the updates on GitHub tasks, I've done that for a few small projects. [elementary's releases page](https://releases.elementary.io) does this as well: https://github.com/elementary/releases

**Comment by GamerKingFaiz** [comment]
I'm not in control of any of the backends at this point. I just leverage the [HowLongToBeat npm package](https://github.com/ckatzorke/howlongtobeat) and the [OpenCritic API](https://app.swaggerhub.com/apis-docs/OpenCritic/OpenCritic-API/0.1.0#/).

Implementing a database/cache for this project is way beyond the current scope of this project.
