### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by beckyandcloud** [GamerKingFaiz/shouldiplay#13]
It's been two days since any page of the website is loading forever, and nothing happens.
Is the website down forever?

**Comment by GamerKingFaiz** [comment]
Thank you for bringing this to my attention! The issue should be fixed now, but don't hesitate to reach out if it breaks again. I'm unsure if my fix will work permanently.

**Comment by beckyandcloud** [comment]
It's back! Thanks for your work on this ♥

Le dim. 4 août 2024 à 18:09, Faiz-ur Rahman ***@***.***> a
écrit :
