### ISSUE TITLE
Issues with showing game lengths of Single player only games

### ISSUE THREAD

**Issue by tejapoth** [GamerKingFaiz/shouldiplay#9]
I noticed this with Single player only titles such as Mass effect Legendary edition where it shows Co. Op & Vs. with no game length. 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/34321739/202951974-2ed12c0f-dc26-4ec9-8f64-ec8d314f5874.png">

But in howlongtobeat its only single player with a range of game length!
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/34321739/202952081-eca5050f-f07a-4881-b7de-1de0e093f9ff.png">

Please fix this if possible!

**Comment by GamerKingFaiz** [comment]
Thanks for the report!

My original logic was just checking to see if HLTB reported the `game_type` as `game`, if not then display it as a `multiplayer` game.
Mass Effect Legendary Edition was classified as a `compilation` game on HLTB, so I added that to the logic.

Should be fixed now!

**Comment by tejapoth** [comment]
Ohh makes sense! Thanks!
